# Generated by Django 2.2.5 on 2019-09-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='学科名称')),
                ('intr', models.TextField(default='this is introdaction', max_length=512, verbose_name='学科介绍')),
                ('create_date', models.DateField(null=True, verbose_name='学科创建时间')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热门')),
            ],
            options={
                'verbose_name': '学科名称',
                'verbose_name_plural': '学科名称',
                'db_table': 'tb_subject',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('email', models.CharField(blank=True, default='', max_length=255, verbose_name='邮箱')),
                ('tel', models.CharField(max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('detail', models.TextField(blank=True, max_length=512, verbose_name='详情')),
                ('photo', models.CharField(default='', max_length=1023, verbose_name='照片')),
                ('good_count', models.IntegerField(default=0, verbose_name='好评数')),
                ('bad_count', models.ImageField(default=0, upload_to='', verbose_name='差评数')),
                ('subject', models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.PROTECT, to='vote.Subject', verbose_name='所属学科')),
            ],
            options={
                'verbose_name': '老师',
                'verbose_name_plural': '老师',
                'db_table': 'tb_teacher',
            },
        ),
    ]
